"""BrainVision equipment ROI definitions.

This module provides ROI definitions for BrainVision recording systems,
adapted from the NICE pipeline. Includes 32-channel, 128-channel, and
11-channel monkey configurations.

References
----------
Adapted from NICE pipeline:
/site/bckp/next_icm/nice_ext/equipments/brainvision.py
"""

import numpy as np

from .rois import define_rois

# BrainVision 32-channel system ROI definitions (0-indexed)
_bv_32_rois = {
    "p3a": np.array([3, 4, 7, 8, 12, 17, 18]),
    "p3b": np.array([7, 8, 12, 17, 18, 22, 23, 24]),
    "mmn": np.array([3, 4, 7, 8, 12, 17, 18]),
    "cnv": np.array([3, 4, 7, 8, 12, 17, 18]),
    "Fz": np.array([3, 4, 7, 8]),
    "Cz": np.array([7, 8, 12, 17, 18]),
    "Pz": np.array([17, 18, 22, 23, 24]),
    "scalp": np.arange(31),
    "nonscalp": np.array([]),
    "Fp1": np.array([]),
    "Fp2": np.array([]),
    "F3": np.array([]),
    "F4": np.array([]),
    "C3": np.array([]),
    "C4": np.array([]),
    "P3": np.array([]),
    "P4": np.array([]),
    "T5": np.array([]),
    "T6": np.array([]),
    "Oz": np.array([]),
}

# BrainVision 128-channel system ROI definitions (0-indexed)
# For 128-channel system, all channels are used for all ROIs
_bv_128_rois = {
    "p3a": np.arange(128),
    "p3b": np.arange(128),
    "mmn": np.arange(128),
    "cnv": np.arange(128),
    "Fz": np.arange(128),
    "Cz": np.arange(128),
    "Pz": np.arange(128),
    "scalp": np.arange(128),
    "nonscalp": np.array([]),
    "Fp1": np.array([]),
    "Fp2": np.array([]),
    "F3": np.array([]),
    "F4": np.array([]),
    "C3": np.array([]),
    "C4": np.array([]),
    "P3": np.array([]),
    "P4": np.array([]),
    "T5": np.array([]),
    "T6": np.array([]),
    "Oz": np.array([]),
}

# BrainVision 11-channel monkey configuration ROI definitions (0-indexed)
_bv_11monkey_rois = {
    "p3a": np.arange(11),
    "p3b": np.arange(11),
    "mmn": np.arange(11),
    "cnv": np.arange(11),
    "Fz": np.arange(11),
    "Cz": np.arange(11),
    "Pz": np.arange(11),
    "scalp": np.arange(11),
    "nonscalp": np.array([]),
    "Fp1": np.array([]),
    "Fp2": np.array([]),
    "F3": np.array([]),
    "F4": np.array([]),
    "C3": np.array([]),
    "C4": np.array([]),
    "P3": np.array([]),
    "P4": np.array([]),
    "T5": np.array([]),
    "T6": np.array([]),
    "Oz": np.array([]),
}


def register_brainvision_equipments():
    """Register all BrainVision equipment ROI definitions.

    This function should be called during module initialization to populate
    the ROI registry with BrainVision equipment definitions.
    """
    # BrainVision 32-channel naming
    bv_32_ch_names = [
        "Fp1",
        "Fp2",
        "F7",
        "F3",
        "F4",
        "F8",
        "FC5",
        "FC1",
        "FC2",
        "FC6",
        "T7",
        "C3",
        "Cz",
        "C4",
        "T8",
        "TP9",
        "CP5",
        "CP1",
        "CP2",
        "CP6",
        "TP10",
        "P7",
        "P3",
        "Pz",
        "P4",
        "P8",
        "PO9",
        "O1",
        "Oz",
        "O2",
        "PO10",
    ]

    # BrainVision 11-channel monkey configuration
    bv_11monkey_ch_names = [
        "Fp1",
        "Fp2",
        "F3",
        "C4",
        "T3",
        "T4",
        "P3",
        "P4",
        "Pz",
        "Oz",
        "O2",
    ]

    # BrainVision 128-channel naming (complex with h-variants)
    bv_128_ch_names = [
        "Fp1",
        "Fz",
        "F3",
        "F7",
        "FT9",
        "FC5",
        "FC1",
        "C3",
        "T7",
        "TP9",
        "CP5",
        "CP1",
        "Pz",
        "P3",
        "P7",
        "O1",
        "Oz",
        "O2",
        "P4",
        "P8",
        "TP10",
        "CP6",
        "CP2",
        "Cz",
        "C4",
        "T8",
        "FT10",
        "FC6",
        "FC2",
        "F4",
        "F8",
        "Fp2",
        "AF7",
        "AF3",
        "AFz",
        "F1",
        "F5",
        "FT7",
        "FC3",
        "FCz",
        "C1",
        "C5",
        "TP7",
        "CP3",
        "P1",
        "P5",
        "PO7",
        "PO3",
        "POz",
        "PO4",
        "PO8",
        "P6",
        "P2",
        "CPz",
        "CP4",
        "TP8",
        "C6",
        "C2",
        "FC4",
        "FT8",
        "F6",
        "F2",
        "AF4",
        "AF8",
        "F9",
        "AFF1h",
        "FFC1h",
        "FFC5h",
        "FTT7h",
        "FCC3h",
        "CCP1h",
        "CCP5h",
        "TPP7h",
        "P9",
        "PPO9h",
        "PO9",
        "I1",
        "OI1h",
        "PPO1h",
        "CPP3h",
        "CPP4h",
        "PPO2h",
        "OI2h",
        "I2",
        "PO10",
        "PPO10h",
        "P10",
        "TPP8h",
        "CCP6h",
        "CCP2h",
        "FCC4h",
        "FTT8h",
        "FFC6h",
        "FFC2h",
        "AFF2h",
        "F10",
        "AFp1",
        "AFF5h",
        "FFT9h",
        "FFT7h",
        "FFC3h",
        "FCC1h",
        "FCC5h",
        "FTT9h",
        "TTP7h",
        "CCP3h",
        "CPP1h",
        "CPP5h",
        "TPP9h",
        "PPO5h",
        "POO1",
        "POO9h",
        "POO10h",
        "POO2",
        "PPO6h",
        "TPP10h",
        "CPP6h",
        "CPP2h",
        "CCP4h",
        "TTP8h",
        "FTT10h",
        "FCC6h",
        "FCC2h",
        "FFC4h",
        "FFT8h",
        "FFT10h",
        "AFF6h",
        "AFp2",
    ]

    define_rois("brainvision/32", _bv_32_rois, ch_names=bv_32_ch_names)
    define_rois("brainvision/128", _bv_128_rois, ch_names=bv_128_ch_names)
    define_rois(
        "brainvision/11monkey",
        _bv_11monkey_rois,
        ch_names=bv_11monkey_ch_names,
    )


# Auto-register on import
register_brainvision_equipments()
