"""Test WindowDecoding marker against NICE reference output.

This test validates that Junifer's WindowDecoding marker produces identical
results to NICE's WindowDecoding marker by:
1. Loading stored synthetic EEG data and NICE reference output
2. Running Junifer WindowDecoding with exact same parameters
3. Comparing outputs to ensure perfect equivalence

Reference data is generated by generate_window_decoding_reference.py
"""

import pickle
from pathlib import Path

import mne
import numpy as np
import pytest

from junifer_eeg.markers.window_decoding import WindowDecoding


def check_window_decoding_equivalence(
    nice_output: np.ndarray,
    junifer_output: np.ndarray,
    marker_name: str,
    tolerance: float = 0.01,
) -> bool:
    """Check that WindowDecoding outputs match.

    Parameters
    ----------
    nice_output : np.ndarray
        NICE WindowDecoding scores (n_folds,)
    junifer_output : np.ndarray
        Junifer WindowDecoding output (1, 1) scalar
    marker_name : str
        Name of marker for reporting
    tolerance : float
        Maximum relative error in percentage (default: 0.01%)

    Returns
    -------
    bool
        True if outputs match within tolerance
    """
    print(f"\n{'=' * 80}")
    print(f"VALIDATING: {marker_name}")
    print(f"{'=' * 80}")

    print("\nShape comparison:")
    print(f"  NICE:    {nice_output.shape}")
    print(f"  Junifer: {junifer_output.shape}")

    # NICE returns (n_folds,) array, Junifer returns (1, 1) scalar
    # Compare mean scores for equivalence
    nice_mean = np.mean(nice_output)
    junifer_scalar = junifer_output[0, 0]

    print("\nValue comparison:")
    print(f"  NICE mean:    {nice_mean:.6f}")
    print(f"  NICE scores:  {nice_output}")
    print(f"  Junifer mean: {junifer_scalar:.6f}")

    # Compute relative error
    abs_diff = np.abs(nice_mean - junifer_scalar)
    rel_diff = abs_diff / (np.abs(nice_mean) + 1e-12) * 100

    print(f"  Absolute difference: {abs_diff:.6e}")
    print(f"  Relative error:      {rel_diff:.4f}%")

    if rel_diff < tolerance:
        print(
            f"\n✅ PERFECT MATCH: {marker_name} ({rel_diff:.4f}% < {tolerance}%)"
        )
        return True
    elif rel_diff < 1.0:
        print(f"\n✅ EXCELLENT MATCH: {marker_name} ({rel_diff:.4f}% error)")
        return True
    else:
        print(f"\n❌ MISMATCH: {marker_name} ({rel_diff:.4f}% error)")

        # Additional diagnostics
        print("\nDiagnostics:")
        print(
            f"  NICE min/max:  {np.min(nice_output):.6f} / {np.max(nice_output):.6f}"
        )
        print(f"  NICE std:      {np.std(nice_output):.6f}")
        print(
            "  Expected:      NICE and Junifer should have identical mean scores"
        )

        return False


class TestWindowDecodingReference:
    """Test WindowDecoding marker against NICE reference data."""

    @classmethod
    def setup_class(cls):
        """Load reference data for WindowDecoding marker."""
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "window_decoding_reference.pkl"

        if not reference_file.exists():
            pytest.skip(
                f"Reference file not found: {reference_file}. "
                "Run generate_window_decoding_reference.py first."
            )

        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

        print("\n" + "=" * 80)
        print("LOADED REFERENCE DATA FOR WINDOW DECODING")
        print("=" * 80)
        print(f"Marker: {cls.reference_data['marker_name']}")
        print(f"NICE output shape: {cls.reference_data['nice_output_shape']}")
        print(f"Data params: {cls.reference_data['data_params']}")

    def test_window_decoding_equivalence(self):
        """Test that Junifer WindowDecoding matches NICE reference."""
        # Step 1: Recreate epochs from stored data
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            event_id=epochs_data["event_id"],  # Make sure to include event_id
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        print(f"Recreated epochs: {epochs.get_data().shape}")
        print(f"Recreated epochs event_id: {epochs.event_id}")

        # Step 2: Get Junifer parameters
        junifer_params = self.reference_data["junifer_params"].copy()

        print("\nJunifer parameters:")
        for key, value in junifer_params.items():
            print(f"  {key}: {value}")

        # Step 3: Create Junifer WindowDecoding marker
        junifer_marker = WindowDecoding(**junifer_params)

        # Step 4: Run Junifer marker
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        print("\nRunning Junifer WindowDecoding marker...")
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["windowdecoding"]["data"]
        print(f"Junifer output shape: {junifer_output.shape}")

        # Step 5: Get NICE reference output
        nice_output = self.reference_data["nice_output"]
        print(f"NICE reference shape: {nice_output.shape}")

        # Step 6: Compare outputs
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_window_decoding_equivalence(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )

        # Step 7: Assert for pytest
        assert match, (
            f"Junifer WindowDecoding output does not match NICE reference "
            f"within {tolerance}% tolerance"
        )

    def test_window_decoding_with_roi(self):
        """Test WindowDecoding with ROI filtering."""
        # Step 1: Recreate epochs from stored data
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            event_id=epochs_data["event_id"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )

        # Step 2: Get Junifer parameters and add ROI
        junifer_params = self.reference_data["junifer_params"].copy()

        # Use only first 8 channels as ROI
        ch_names = epochs.ch_names
        roi_channels = ch_names[:8]  # First 8 out of 16 channels
        junifer_params["rois"] = roi_channels

        print(f"\nTesting with ROI: {roi_channels}")

        # Step 3: Create Junifer WindowDecoding marker with ROI
        junifer_marker = WindowDecoding(**junifer_params)

        # Step 4: Run Junifer marker
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        print("\nRunning Junifer WindowDecoding marker with ROI...")
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["windowdecoding"]["data"]

        # Step 5: Verify output is reasonable (should be different from full channels)
        # We can't compare to NICE reference since we changed the ROI,
        # but we can verify the output is in a reasonable range
        score = junifer_output[0, 0]
        print(f"ROI-restricted score: {score:.6f}")

        # Score should be between 0.5 (chance) and 1.0 (perfect)
        assert 0.5 <= score <= 1.0, (
            f"WindowDecoding score {score:.6f} outside reasonable range [0.5, 1.0]"
        )

        print("✅ ROI test passed - score in reasonable range")

    def test_window_decoding_missing_conditions(self):
        """Test WindowDecoding behavior with missing conditions."""
        # Step 1: Create epochs with only one condition
        epochs_data = self.reference_data["epochs_data"]

        # Filter to only condition_a epochs
        condition_a_mask = epochs_data["events"][:, 2] == 1
        filtered_data = epochs_data["data"][condition_a_mask]
        filtered_events = epochs_data["events"][condition_a_mask]

        # Create epochs with only condition A
        epochs = mne.EpochsArray(
            filtered_data,
            epochs_data["info"],
            events=filtered_events,
            event_id={"condition_a": 1},
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        print(
            f"Created epochs with single condition: {epochs.get_data().shape}"
        )

        # Step 2: Get Junifer parameters
        junifer_params = self.reference_data["junifer_params"].copy()

        # Step 3: Create Junifer WindowDecoding marker
        junifer_marker = WindowDecoding(**junifer_params)

        # Step 4: Run Junifer marker
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        print("\nRunning Junifer WindowDecoding with missing condition...")
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["windowdecoding"]["data"]

        # Step 5: Should return chance level (0.5) for missing conditions
        expected_score = 0.5
        actual_score = junifer_output[0, 0]

        print(f"Expected chance level: {expected_score}")
        print(f"Actual score: {actual_score}")

        assert actual_score == expected_score, (
            f"Expected {expected_score} for missing conditions, got {actual_score}"
        )

        print("✅ Missing conditions test passed - returned chance level")


if __name__ == "__main__":
    # Allow running this test file directly for debugging
    pytest.main([__file__, "-v", "-s"])
