"""Test junifer_eeg markers against NICE reference outputs.

This test suite validates that Junifer markers produce identical results
to NICE markers by:
1. Loading stored synthetic EEG data
2. Loading stored NICE reference outputs
3. Running Junifer markers with exact same parameters
4. Comparing outputs to ensure perfect equivalence

Reference data is generated by generate_reference_data.py
"""

import pickle
import sys
from pathlib import Path

import mne
import numpy as np
import pytest

# Add parent directory to path for helper import
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
from junifer_eeg.markers.contingent_negative_variation import (
    ContingentNegativeVariation,
)
from junifer_eeg.markers.kolmogorov_complexity.kolmogorov_complexity import (
    KolmogorovComplexity,
)
from junifer_eeg.markers.permutation_entropy import (
    PermutationEntropy as PermutationEntropyROIs,
)
from junifer_eeg.markers.power_spectral_density.psd_summary import (
    PowerSpectralDensitySummary,
)
from junifer_eeg.markers.spectral_power import (
    SpectralPowerBands as SpectralPowerBandsROIs,
)
from junifer_eeg.markers.symbolic_mutual_information.symbolic_mutual_information import (
    SymbolicMutualInformation,
)
from junifer_eeg.markers.time_locked.time_locked_contrast import (
    TimeLockedContrast,
)
from junifer_eeg.markers.time_locked.time_locked_topography import (
    TimeLockedTopography,
)
from junifer_eeg.tests.validation.update_tests_helper import (
    convert_legacy_params,
)
from junifer_eeg.tests.validation.update_tests_helper import (
    convert_to_permutation_entropy_rois as convert_permutation_entropy_params,
)
from junifer_eeg.tests.validation.update_tests_helper import (
    convert_to_spectral_power_bands_rois as convert_spectral_power_params,
)


def check_shapes_and_compare(
    nice_data, junifer_data, marker_name, tolerance=0.01
):
    """Check shapes match and compare values.

    This follows the exact comparison logic from validate_all_markers_raw.py

    Args:
        nice_data: Output from NICE marker
        junifer_data: Output from Junifer marker
        marker_name: Name of marker for reporting
        tolerance: Maximum relative error in percentage (default: 0.01%)

    Returns:
        bool: True if shapes and values match within tolerance
    """
    print(f"\n{'=' * 80}")
    print(f"VALIDATING: {marker_name}")
    print(f"{'=' * 80}")

    print("\nShape comparison:")
    print(
        f"  NICE:    {nice_data.shape if hasattr(nice_data, 'shape') else 'scalar'}"
    )
    print(
        f"  Junifer: {junifer_data.shape if hasattr(junifer_data, 'shape') else 'scalar'}"
    )

    # Convert scalars to arrays for consistent handling
    nice_arr = np.atleast_1d(nice_data)
    junifer_arr = np.atleast_1d(junifer_data)

    assert nice_arr.shape == junifer_arr.shape, (
        f"Shape mismatch: NICE {nice_arr.shape} vs Junifer {junifer_arr.shape}"
    )
    print("  ✅ Shapes match!")

    # Compare values
    abs_diff = np.abs(nice_arr - junifer_arr)
    rel_diff = abs_diff / (np.abs(nice_arr) + 1e-12)

    max_rel_error = np.max(rel_diff) * 100
    mean_rel_error = np.mean(rel_diff) * 100

    print("\nValue comparison:")
    print(f"  NICE mean:    {np.mean(nice_arr):.6e}")
    print(f"  Junifer mean: {np.mean(junifer_arr):.6e}")
    print(f"  Max relative error:  {max_rel_error:.4f}%")
    print(f"  Mean relative error: {mean_rel_error:.4f}%")

    assert max_rel_error < 1.0, (
        f"MISMATCH: {marker_name} ({max_rel_error:.4f}% error)\n\n  Worst case at index {np.unravel_index(np.argmax(abs_diff), abs_diff.shape) if nice_arr.size > 1 else 'scalar'}\n  NICE value: {nice_arr[np.unravel_index(np.argmax(abs_diff), abs_diff.shape) if nice_arr.size > 1 else ()]:.6f}\n  Junifer value: {junifer_arr[np.unravel_index(np.argmax(abs_diff), abs_diff.shape) if nice_arr.size > 1 else ()]:.6f}\n  Absolute diff: {abs_diff[np.unravel_index(np.argmax(abs_diff), abs_diff.shape) if nice_arr.size > 1 else ()]:.6e}\n  Relative diff: {rel_diff[np.unravel_index(np.argmax(abs_diff), abs_diff.shape) if nice_arr.size > 1 else ()]:.4f}%"
    )

    if max_rel_error < 0.01:
        print(
            f"\n✅ PERFECT MATCH: {marker_name} ({max_rel_error:.4f}% error)"
        )
    else:
        print(
            f"\n✅ EXCELLENT MATCH: {marker_name} ({max_rel_error:.4f}% error)"
        )

    if nice_arr.size > 1:
        worst_idx = np.unravel_index(np.argmax(rel_diff), rel_diff.shape)
        print(f"\nWorst case at index {worst_idx}:")
        print(f"  NICE value:    {nice_arr[worst_idx]:.6e}")
        print(f"  Junifer value: {junifer_arr[worst_idx]:.6e}")
        print(f"  Relative diff: {rel_diff[worst_idx] * 100:.4f}%")
    else:
        print("\nScalar comparison:")
        print(f"  NICE value:    {nice_arr[0]:.6e}")
        print(f"  Junifer value: {junifer_arr[0]:.6e}")
        print(f"  Relative diff: {rel_diff[0] * 100:.4f}%")

    return True


class TestSpectralPowerDelta:
    """Test Spectral Power - Delta band marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        """Load reference data for spectral power delta marker."""
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "spectral_power_delta_reference.pkl"

        if not reference_file.exists():
            pytest.skip(
                f"Reference file not found: {reference_file}. "
                "Run generate_reference_data.py first."
            )

        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

        print("\n" + "=" * 80)
        print("LOADED REFERENCE DATA FOR SPECTRAL POWER - DELTA BAND")
        print("=" * 80)
        print(f"Marker: {cls.reference_data['marker_name']}")
        print(f"Description: {cls.reference_data['description']}")
        print(f"NICE output shape: {cls.reference_data['nice_output_shape']}")
        print(f"Tolerance: {cls.reference_data['comparison_tolerance']}%")

    def test_spectral_power_delta_equivalence(self):
        """Test that Junifer SpectralPower produces identical output to NICE.

        This test:
        1. Loads stored synthetic EEG data
        2. Recreates MNE Epochs object
        3. Runs Junifer SpectralPower with stored parameters
        4. Compares output to stored NICE output
        5. Asserts perfect match within tolerance
        """
        print("\n" + "=" * 80)
        print("TESTING SPECTRAL POWER - DELTA BAND")
        print("=" * 80)

        # Step 1: Recreate epochs from stored data
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        print(f"\nRecreated epochs: {epochs.get_data().shape}")

        # Step 2: Get Junifer parameters
        junifer_params = self.reference_data["junifer_params"]
        print("\nJunifer parameters:")
        for key, value in junifer_params.items():
            print(f"  {key}: {value}")

        # Step 3: Create Junifer marker with exact parameters
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(junifer_params)
        junifer_marker = SpectralPowerBandsROIs(**new_params)

        # Step 4: Run Junifer marker
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        print("\nRunning Junifer SpectralPower marker...")
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        print(f"Junifer output shape: {junifer_output.shape}")

        # Step 5: Get NICE reference output
        nice_output = self.reference_data["nice_output"]
        print(f"NICE output shape: {nice_output.shape}")

        # Step 6: Compare using exact logic from validate_all_markers_raw.py
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )

        # Step 7: Assert for pytest
        assert match, (
            f"Junifer output does not match NICE reference within {tolerance}% tolerance"
        )

    def test_output_values_reasonable(self):
        """Additional sanity checks on output values."""
        # Get outputs
        nice_output = self.reference_data["nice_output"]

        # Check reasonable ranges for spectral power in dB
        print("\nSanity checks on output values:")
        print(f"  Min value: {nice_output.min():.2f} dB")
        print(f"  Max value: {nice_output.max():.2f} dB")
        print(f"  Mean value: {nice_output.mean():.2f} dB")

        # Spectral power in dB should be negative (typically -150 to 0 dB)
        assert np.all(nice_output < 10), "Spectral power in dB should be < 10"
        assert np.all(nice_output > -200), (
            "Spectral power in dB should be > -200"
        )
        print("  ✅ Values are in reasonable range for spectral power (dB)")


# ============================================================================
# SPECTRAL POWER - NON-NORMALIZED (REMAINING 4 BANDS)
# ============================================================================


class TestSpectralPowerTheta:
    """Test Spectral Power - Theta band marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "spectral_power_theta_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerAlpha:
    """Test Spectral Power - Alpha band marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "spectral_power_alpha_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerBeta:
    """Test Spectral Power - Beta band marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "spectral_power_beta_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerGamma:
    """Test Spectral Power - Gamma band marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "spectral_power_gamma_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# SPECTRAL POWER - NORMALIZED (5 BANDS)
# ============================================================================


class TestSpectralPowerNormalizedDelta:
    """Test Normalized Spectral Power - Delta_n band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "spectral_power_normalized_delta_n_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerNormalizedTheta:
    """Test Normalized Spectral Power - Theta_n band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "spectral_power_normalized_theta_n_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerNormalizedAlpha:
    """Test Normalized Spectral Power - Alpha_n band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "spectral_power_normalized_alpha_n_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerNormalizedBeta:
    """Test Normalized Spectral Power - Beta_n band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "spectral_power_normalized_beta_n_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSpectralPowerNormalizedGamma:
    """Test Normalized Spectral Power - Gamma_n band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "spectral_power_normalized_gamma_n_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# CNV (CONTINGENT NEGATIVE VARIATION)
# ============================================================================


class TestCNV:
    """Test CNV (Contingent Negative Variation) marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "cnv_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = ContingentNegativeVariation(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["cnvslope"][
            "data"
        ]  # CNV uses "cnvslope" key
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# KOLMOGOROV COMPLEXITY
# ============================================================================


class TestKolmogorovComplexity:
    """Test Kolmogorov Complexity marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "kolmogorov_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = KolmogorovComplexity(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["kolmogorovcomplexity"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# TIME-LOCKED TOPOGRAPHY (P1, P3a, P3b)
# ============================================================================


class TestTimeLockedTopographyP1:
    """Test Time-Locked Topography - P1 marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "time_locked_topo_p1_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = TimeLockedTopography(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedtopo"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedTopographyP3a:
    """Test Time-Locked Topography - P3a marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "time_locked_topo_p3a_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = TimeLockedTopography(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedtopo"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedTopographyP3b:
    """Test Time-Locked Topography - P3b marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "time_locked_topo_p3b_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = TimeLockedTopography(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedtopo"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# PERMUTATION ENTROPY (BASE + 4 PER-BAND)
# ============================================================================


class TestPermutationEntropy:
    """Test Permutation Entropy (base) marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "permutation_entropy_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old PermutationEntropy parameters to new PermutationEntropyROIs format
        new_params = convert_permutation_entropy_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = PermutationEntropyROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["permutationentropy"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPermutationEntropyTheta:
    """Test Permutation Entropy - Theta band marker."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "permutation_entropy_theta_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old PermutationEntropy parameters to new PermutationEntropyROIs format
        new_params = convert_permutation_entropy_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = PermutationEntropyROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["permutationentropy"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPermutationEntropyAlpha:
    """Test Permutation Entropy - Alpha band marker."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "permutation_entropy_alpha_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old PermutationEntropy parameters to new PermutationEntropyROIs format
        new_params = convert_permutation_entropy_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = PermutationEntropyROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["permutationentropy"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPermutationEntropyBeta:
    """Test Permutation Entropy - Beta band marker."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "permutation_entropy_beta_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old PermutationEntropy parameters to new PermutationEntropyROIs format
        new_params = convert_permutation_entropy_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = PermutationEntropyROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["permutationentropy"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPermutationEntropyGamma:
    """Test Permutation Entropy - Gamma band marker."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "permutation_entropy_gamma_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old PermutationEntropy parameters to new PermutationEntropyROIs format
        new_params = convert_permutation_entropy_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = PermutationEntropyROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["permutationentropy"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# PSD SUMMARY (MSF, SEF90, SEF95)
# ============================================================================


class TestPSDSummaryMSF:
    """Test PSD Summary - MSF marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "psd_summary_msf_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = PowerSpectralDensitySummary(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        # PSD Summary returns data as (n_epochs, n_channels) matrix
        junifer_output = junifer_result["psdsummary"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPSDSummarySEF90:
    """Test PSD Summary - SEF90 marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "psd_summary_sef90_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = PowerSpectralDensitySummary(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        # PSD Summary returns data as (n_epochs, n_channels) matrix
        junifer_output = junifer_result["psdsummary"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestPSDSummarySEF95:
    """Test PSD Summary - SEF95 marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "psd_summary_sef95_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        junifer_marker = PowerSpectralDensitySummary(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        # PSD Summary returns data as (n_epochs, n_channels) matrix
        junifer_output = junifer_result["psdsummary"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# TIME-LOCKED CONTRAST (7 MARKERS)
# ============================================================================


class TestTimeLockedContrastLSGS_LDGD:
    """Test Time-Locked Contrast - LSGS vs LDGD."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_lsgs_ldgd_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        # TLC with aggregation returns scalar (natural shape)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastLSGD_LDGS:
    """Test Time-Locked Contrast - LSGD vs LDGS."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_lsgd_ldgs_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastLD_LS:
    """Test Time-Locked Contrast - LD vs LS (deviant vs standard)."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_ld_ls_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastMMN:
    """Test Time-Locked Contrast - MMN (Mismatch Negativity)."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_mmn_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastP3a:
    """Test Time-Locked Contrast - P3a."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_p3a_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastGD_GS:
    """Test Time-Locked Contrast - GD vs GS (goal vs standard)."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_gd_gs_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestTimeLockedContrastP3b:
    """Test Time-Locked Contrast - P3b."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "time_locked_contrast_p3b_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            event_id=epochs_data["event_id"],
            verbose=False,
        )
        junifer_marker = TimeLockedContrast(
            **convert_legacy_params(self.reference_data["junifer_params"])
        )
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["timelockedcontrast"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# SHANNON ENTROPY (1 MARKER)
# ============================================================================


class TestShannonEntropy:
    """Test Shannon Entropy (spectral entropy) marker against NICE reference."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = reference_dir / "shannon_entropy_reference.pkl"
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Convert old SpectralPower parameters to new SpectralPowerBandsROIs format
        new_params = convert_spectral_power_params(
            self.reference_data["junifer_params"]
        )
        junifer_marker = SpectralPowerBandsROIs(**new_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_output = junifer_result["spectralpower"]["data"]
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


# ============================================================================
# SYMBOLIC MUTUAL INFORMATION (5 MARKERS)
# ============================================================================


class TestSymbolicMutualInformation:
    """Test Symbolic Mutual Information - No frequency filtering."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "symbolic_mutual_information_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Filter out old parameter names for new refactored marker
        junifer_params = convert_legacy_params(
            self.reference_data["junifer_params"]
        )
        junifer_params.pop("channel_method", None)
        junifer_params.pop("trial_method", None)
        junifer_params.pop("connectivity_aggregation_method", None)
        junifer_params.pop("rois", None)  # Not used in base marker

        # Convert old tau parameter to new taus parameter for refactored marker
        if "tau" in junifer_params:
            junifer_params["taus"] = junifer_params.pop("tau")

        junifer_marker = SymbolicMutualInformation(**junifer_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        # SMI returns flattened upper triangular - unflatten to 3D tensor
        junifer_data_flat = junifer_result["symbolicmutualinformation"]["data"]
        n_epochs = junifer_data_flat.shape[0]
        n_channels = self.reference_data["nice_output"].shape[0]
        # Reconstruct full symmetric matrices from upper triangular
        junifer_data_3d = np.zeros((n_epochs, n_channels, n_channels))
        upper_tri_indices = np.triu_indices(n_channels, k=1)
        for epoch_idx in range(n_epochs):
            upper_tri_values = junifer_data_flat[epoch_idx]
            junifer_data_3d[epoch_idx][upper_tri_indices] = upper_tri_values
            junifer_data_3d[epoch_idx] = (
                junifer_data_3d[epoch_idx] + junifer_data_3d[epoch_idx].T
            )
        # Transpose to match NICE format: (n_channels, n_channels, n_epochs)
        junifer_output = junifer_data_3d.transpose(1, 2, 0)
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSymbolicMutualInformationTheta:
    """Test Symbolic Mutual Information - Theta band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "symbolic_mutual_information_theta_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Filter out old parameter names for new refactored marker
        junifer_params = convert_legacy_params(
            self.reference_data["junifer_params"]
        )
        junifer_params.pop("channel_method", None)
        junifer_params.pop("trial_method", None)
        junifer_params.pop("connectivity_aggregation_method", None)
        junifer_params.pop("rois", None)  # Not used in base marker

        # Convert old tau parameter to new taus parameter for refactored marker
        if "tau" in junifer_params:
            junifer_params["taus"] = junifer_params.pop("tau")

        junifer_marker = SymbolicMutualInformation(**junifer_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_data_flat = junifer_result["symbolicmutualinformation"]["data"]
        n_epochs = junifer_data_flat.shape[0]
        n_channels = self.reference_data["nice_output"].shape[0]
        junifer_data_3d = np.zeros((n_epochs, n_channels, n_channels))
        upper_tri_indices = np.triu_indices(n_channels, k=1)
        for epoch_idx in range(n_epochs):
            upper_tri_values = junifer_data_flat[epoch_idx]
            junifer_data_3d[epoch_idx][upper_tri_indices] = upper_tri_values
            junifer_data_3d[epoch_idx] = (
                junifer_data_3d[epoch_idx] + junifer_data_3d[epoch_idx].T
            )
        junifer_output = junifer_data_3d.transpose(1, 2, 0)
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSymbolicMutualInformationAlpha:
    """Test Symbolic Mutual Information - Alpha band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "symbolic_mutual_information_alpha_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Filter out old parameter names for new refactored marker
        junifer_params = convert_legacy_params(
            self.reference_data["junifer_params"]
        )
        junifer_params.pop("channel_method", None)
        junifer_params.pop("trial_method", None)
        junifer_params.pop("connectivity_aggregation_method", None)
        junifer_params.pop("rois", None)  # Not used in base marker

        # Convert old tau parameter to new taus parameter for refactored marker
        if "tau" in junifer_params:
            junifer_params["taus"] = junifer_params.pop("tau")

        junifer_marker = SymbolicMutualInformation(**junifer_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_data_flat = junifer_result["symbolicmutualinformation"]["data"]
        n_epochs = junifer_data_flat.shape[0]
        n_channels = self.reference_data["nice_output"].shape[0]
        junifer_data_3d = np.zeros((n_epochs, n_channels, n_channels))
        upper_tri_indices = np.triu_indices(n_channels, k=1)
        for epoch_idx in range(n_epochs):
            upper_tri_values = junifer_data_flat[epoch_idx]
            junifer_data_3d[epoch_idx][upper_tri_indices] = upper_tri_values
            junifer_data_3d[epoch_idx] = (
                junifer_data_3d[epoch_idx] + junifer_data_3d[epoch_idx].T
            )
        junifer_output = junifer_data_3d.transpose(1, 2, 0)
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSymbolicMutualInformationBeta:
    """Test Symbolic Mutual Information - Beta band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "symbolic_mutual_information_beta_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Filter out old parameter names for new refactored marker
        junifer_params = convert_legacy_params(
            self.reference_data["junifer_params"]
        )
        junifer_params.pop("channel_method", None)
        junifer_params.pop("trial_method", None)
        junifer_params.pop("connectivity_aggregation_method", None)
        junifer_params.pop("rois", None)  # Not used in base marker

        # Convert old tau parameter to new taus parameter for refactored marker
        if "tau" in junifer_params:
            junifer_params["taus"] = junifer_params.pop("tau")

        junifer_marker = SymbolicMutualInformation(**junifer_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_data_flat = junifer_result["symbolicmutualinformation"]["data"]
        n_epochs = junifer_data_flat.shape[0]
        n_channels = self.reference_data["nice_output"].shape[0]
        junifer_data_3d = np.zeros((n_epochs, n_channels, n_channels))
        upper_tri_indices = np.triu_indices(n_channels, k=1)
        for epoch_idx in range(n_epochs):
            upper_tri_values = junifer_data_flat[epoch_idx]
            junifer_data_3d[epoch_idx][upper_tri_indices] = upper_tri_values
            junifer_data_3d[epoch_idx] = (
                junifer_data_3d[epoch_idx] + junifer_data_3d[epoch_idx].T
            )
        junifer_output = junifer_data_3d.transpose(1, 2, 0)
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


class TestSymbolicMutualInformationGamma:
    """Test Symbolic Mutual Information - Gamma band."""

    @classmethod
    def setup_class(cls):
        reference_dir = Path(__file__).parent / "reference_data"
        reference_file = (
            reference_dir / "symbolic_mutual_information_gamma_reference.pkl"
        )
        if not reference_file.exists():
            pytest.skip(f"Reference file not found: {reference_file}")
        with open(reference_file, "rb") as f:
            cls.reference_data = pickle.load(f)

    def test_equivalence(self):
        epochs_data = self.reference_data["epochs_data"]
        epochs = mne.EpochsArray(
            epochs_data["data"],
            epochs_data["info"],
            events=epochs_data["events"],
            tmin=epochs_data["tmin"],
            verbose=False,
        )
        # Filter out old parameter names for new refactored marker
        junifer_params = convert_legacy_params(
            self.reference_data["junifer_params"]
        )
        junifer_params.pop("channel_method", None)
        junifer_params.pop("trial_method", None)
        junifer_params.pop("connectivity_aggregation_method", None)
        junifer_params.pop("rois", None)  # Not used in base marker

        # Convert old tau parameter to new taus parameter for refactored marker
        if "tau" in junifer_params:
            junifer_params["taus"] = junifer_params.pop("tau")

        junifer_marker = SymbolicMutualInformation(**junifer_params)
        input_dict = {
            "data": epochs,
            "meta": {
                "subject": "test",
                "session": "01",
                "task": "test",
                "run": "01",
            },
        }
        junifer_result = junifer_marker.compute(input_dict)
        junifer_data_flat = junifer_result["symbolicmutualinformation"]["data"]
        n_epochs = junifer_data_flat.shape[0]
        n_channels = self.reference_data["nice_output"].shape[0]
        junifer_data_3d = np.zeros((n_epochs, n_channels, n_channels))
        upper_tri_indices = np.triu_indices(n_channels, k=1)
        for epoch_idx in range(n_epochs):
            upper_tri_values = junifer_data_flat[epoch_idx]
            junifer_data_3d[epoch_idx][upper_tri_indices] = upper_tri_values
            junifer_data_3d[epoch_idx] = (
                junifer_data_3d[epoch_idx] + junifer_data_3d[epoch_idx].T
            )
        junifer_output = junifer_data_3d.transpose(1, 2, 0)
        nice_output = self.reference_data["nice_output"]
        tolerance = self.reference_data["comparison_tolerance"]
        match = check_shapes_and_compare(
            nice_output,
            junifer_output,
            self.reference_data["marker_name"],
            tolerance=tolerance,
        )
        assert match, f"Output does not match within {tolerance}% tolerance"


if __name__ == "__main__":
    # Run tests with pytest

    pytest.main([__file__, "-v", "-s"])
